#define CPU_CONFIG_SERIAL "000000008b443c09"

// --- ANGLE DEFINES -----

#define AXIS_1_TOTAL_DGREE 350
#define AXIS_2_TOTAL_DGREE 150
#define AXIS_3_TOTAL_DGREE 150
#define AXIS_4_TOTAL_DGREE 150
#define AXIS_5_TOTAL_DGREE 350

// ------- MODIFIY LIMITS -----------
#define AXIS_1_MIN 0
#define AXIS_1_MAX 255

#define AXIS_2_MIN 0
#define AXIS_2_MAX 255

#define AXIS_3_MIN 0
#define AXIS_3_MAX 255

#define AXIS_4_MIN 0
#define AXIS_4_MAX 255

#define AXIS_5_MIN 0
#define AXIS_5_MAX 255

// --- DONT TOUCH -----
#define STEPPER_1_EN_PIN 39
#define STEPPER_1_DIR_PIN 35
#define STEPPER_1_STEP_PIN 37
#define STEPPER_1_ID 1
#define STEPPER_1_JITTER_THREASHHOLD 20
#define STEPPER_1_INVERT_DIR true
#define STEPPER_1_SKIP_STEP 1
#define STEPPER_1_UPPER_LIMIT AXIS_1_MAX
#define STEPPER_1_LOWER_LIMIT AXIS_1_MIN

#define STEPPER_2_EN_PIN 33
#define STEPPER_2_DIR_PIN 29
#define STEPPER_2_STEP_PIN 31
#define STEPPER_2_ID 2
#define STEPPER_2_JITTER_THREASHHOLD 20
#define STEPPER_2_INVERT_DIR false
#define STEPPER_2_SKIP_STEP 1
#define STEPPER_2_UPPER_LIMIT AXIS_2_MAX
#define STEPPER_2_LOWER_LIMIT AXIS_2_MIN

#define STEPPER_3_EN_PIN 23
#define STEPPER_3_DIR_PIN 27
#define STEPPER_3_STEP_PIN 25
#define STEPPER_3_ID 3
#define STEPPER_3_JITTER_THREASHHOLD 20
#define STEPPER_3_INVERT_DIR true
#define STEPPER_3_SKIP_STEP 1
#define STEPPER_3_UPPER_LIMIT AXIS_3_MAX
#define STEPPER_3_LOWER_LIMIT AXIS_3_MIN

#define STEPPER_4_EN_PIN 41
#define STEPPER_4_DIR_PIN 45
#define STEPPER_4_STEP_PIN 43
#define STEPPER_4_ID 4
#define STEPPER_4_JITTER_THREASHHOLD 20
#define STEPPER_4_INVERT_DIR false
#define STEPPER_4_SKIP_STEP 1 //
#define STEPPER_4_UPPER_LIMIT AXIS_4_MAX
#define STEPPER_4_LOWER_LIMIT AXIS_4_MIN

#define STEPPER_5_EN_PIN 40
#define STEPPER_5_DIR_PIN 44
#define STEPPER_5_STEP_PIN 42
#define STEPPER_5_ID 5
#define STEPPER_5_JITTER_THREASHHOLD 20
#define STEPPER_5_INVERT_DIR false
#define STEPPER_5_SKIP_STEP 1
#define STEPPER_5_UPPER_LIMIT AXIS_5_MAX
#define STEPPER_5_LOWER_LIMIT AXIS_5_MIN
